### ISSUE TITLE
CORS: Allow any app or website to download keys by KeyID

### ISSUE THREAD

**Issue by vitorpamplona** [ehn-digital-green-development/hcert-service-kotlin#1]
Currently, there is no mention of CORS in this application and thus, the default behavior is to block any app trying to access a specific kid `https://xx/ehn/<kid>`, which I believe damages the utility of the project. 

Having an existing kID means a verifier has access to an HCERT with that kID. If the issuer has the key on the database, activating `Access-Control-Allow-Origin: '*' ` for that route allows anyone to download it, facilitating the life of verifiers. 

Entities running this service should be able to easily activate it CORS: `*`

**Comment by dirkx** [comment]
Victor,

I am not sure this is a good idea from a security perspective. 

As any memberstate (or a foreign state actor with an grip on something in the chain, or a normal rogue actor) can get in a position where they can trigger KID or OCSP lookups that are sufficiently unique to start tracking specific citizens or groups.

So one would really want _bulk_ downloads and _bulk_ CRLs - and stay far from 'discovery' and granular fetches.

Also - fetching a few 10's of KBs every night of just the X,Y and KIDs is probably a small price to pay for privacy.

**Comment by vitorpamplona** [comment]
That's a decision states can take, not developers. 

Developers should just allow them to do so if they wish (build a configuration option as requested).

**Comment by dirkx** [comment]
Point taken and understood - however in the EU we labour under the GDPR with requires "Security by Design" and "Privacy by default". So this is indeed something which is the responsibility/legal-liability of/for the developers too.

**Comment by vitorpamplona** [comment]
Sure, but this is neither a security risk or a privacy risk. The information is already public on master lists (privacy is irrelevant) and security is not diminished by sharing public keys freely, one by one.

**Comment by dirkx** [comment]
I think we need to disagree on the "security is not diminished by sharing public keys freely, one by one".

And example of a scenario that concerns us if a citizen somehow gets a QR code on his phone which is signed by a DSC certificate that is completely unique and only used once - to sign that QR.

And that this triggers a KID fetch or a OCSP from the verifier in the field.

Thus informing whoever has visibility of the the KID->Cert or OCSP infra (or the path to it) its traffic a 'ping back' of a certain person showing up near a certain IP address (for example).

**Comment by vitorpamplona** [comment]
But that has nothing to do with this feature. After all, if a verifier needs a new KID download, the app will hit the server for the master list anyway. That will happen no matter what you or states decide on this topic.

**Comment by vitorpamplona** [comment]
In fact, that if the individual download is not allowed by a state, my app will be pinging the master list at every 10mins just to make sure the app has all the keys all the time.

**Comment by asitplus-pteufl** [comment]
@vitorpamplona regarding the service you are referring here, the direct KID download was just a workaround for our demos that we used prior to having our national trust list. this functionality is not going to used by us, its purely there for demonstration purposes. there will be no individual cert download for the austrian backend.

**Comment by vitorpamplona** [comment]
Tracking by the issuer's servers is why I strongly oppose serving keys from any static or dynamic server, this project included. Individual keys should be distributed through DNS Records and the Key ID should be the subdomain name, not a crop of the kID, that will be used to perform a DNS Lookup and get the key from the Lookup itself. 

If we are talking about Security by Design and Privacy by Default, the service provided by this project should never exist. But since it does, the difference between open and close CORS is irrelevant.

**Comment by nodh** [comment]
Removed the endpoint in question, thus closing here.
